amazon_agent:
  inputs: amazon_search
  outputs: amazon_shopping_result

bronners_agent:
  inputs: bronners_search
  outputs: bronners_shopping_result


worldmarket_agent:
  inputs: worldmarket_search
  outputs: worldmarket_shopping_result


minted_agent:
  inputs: minted_search
  outputs: minted_shopping_result


balsamhill_agent:
  inputs: balsamhill_search
  outputs: balsamhill_shopping_result


christmaslightsetc_agent:
  inputs: christmaslightsetc_search
  outputs: christmaslightsetc_shopping_result


notonthehighstreet_agent:
  inputs: notonthehighstreet_search
  outputs: notonthehighstreet_shopping_result